export const STATION_MAP_CONFIG = {
  center: { lng: 10.75, lat: 59.91 },
  zoom: 11,
  minZoom: 2,
  maxZoom: 18,
  zoomSnap: 1,
  // Without this, cluster counts stay visible for 300 ms after their circles are gone.
  fadeDuration: 0,
  tileSize: 256,
  sourceMaxZoom: 19,
  clusterRadius: 60,
  fitPadding: 32,
  fitMaxZoom: 14,
  searchMaxZoom: 16,
  locateZoom: 15,
  focusZoom: 15,
  revealMargin: 32,
  noInsets: { left: 0, bottom: 0 },
  accuracyReferenceZoom: 22,
  iconSize: 16,
  iconPixelRatio: 2,
  availableIconId: 'station-icon-available',
  unavailableIconId: 'station-icon-unavailable',
  tilesSourceId: 'tiles',
  stationsSourceId: 'stations',
  spiderSourceId: 'station-spider',
  searchSourceId: 'search-result',
  userLocationSourceId: 'user-location',
  clusterLayerId: 'station-clusters',
  stationLayerId: 'station-points',
  spiderStationLayerId: 'spider-stations',
} as const;
